export default {
  path: '/task',
  name: '任务管理',
  icon: 'crown',
  access: 'canAdmin',
  // component: "@/pages/Task",
  routes: [
    {
      path: '/task/today',
      name: '今日任务',
      title: '今日任务',
      icon: 'smile',
      component: '@/pages/Task/Today',
    },
    {
      path: '/task/reservation',
      name: '预约任务',
      title: '预约任务',
      icon: 'smile',
      component: '@/pages/Task/Reservation',
    },
    {
      path: '/task/history',
      name: '历史任务',
      title: '历史任务',
      icon: 'smile',
      component: '@/pages/Task/History',
    },
    {
      path: '/task/abnormal',
      name: '异常任务',
      title: '异常任务',
      icon: 'smile',
      component: '@/pages/Task/Abnormal',
    },
    {
      path: '/task/thirdparty',
      name: '第三方任务',
      title: '第三方任务',
      icon: 'smile',
      component: '@/pages/Task/Thirdparty',
    },
    // {
    //   path: "/task/orderDetail",
    //   name: "订单详情",
    //   title: "订单详情",
    //   icon: "smile",
    //   component: "@/pages/Task/OrderDetail",
    // },
  ],
};
